<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crno-bijela tablica</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            border: 2px solid black;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
            min-height: 30px;
        }

        th {
            font-weight: bold;
        }
    </style>
</head>
<body>

    <table>
        <tr>
            <th>Artikl</th>
            <th>Stanje u skladištu</th>
            <th>Cijena</th>
            <th>Potrebno nabaviti</th>
            <th>Cijena u nabavi</th>
            <th>Krajnji rok nabave</th>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>paprika</td>
            <td>1225,25 kg</td>
            <td>0,89 €/kg</td>
            <td style="text-align: center">-</td>
            <td style="text-align: center">-</td>
            <td style="text-align: center">-</td>
        </tr>
        <tr>
            <td>krumpir crveni</td>
            <td>600 kg</td>
            <td>0,57</td>
            <td>3000 kg</td>
            <td>0,35 €/kg</td>
            <td>2024-08-24</td>
        </tr>
        <tr>
            <td>krumpir žuti</td>
            <td>0 kg</td>
            <td style="text-align: center">-</td>
            <td>1200 kg</td>
            <td>0,48 €/kg</td>
            <td>2024-06-12</td>
        </tr>
        <tr>
            <td>krumpir mladi</td>
            <td>260,83 kg</td>
            <td>0,94 €/kg</td>
            <td>6500 kg</td>
            <td>0,50 €/kg</td>
            <td>2024-04-15</td>
        </tr>
        <tr>
            <td>žarulja 20W</td>
            <td>250 komada</td>
            <td>2,74 €/komad</td>
            <td>300 komada</td>
            <td>1,25 € komad</td>
            <td>2024-04-20</td>
        </tr>
    </table>
</body>
</html>
