<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="stil.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Zadatak 3</title>
</head>
<body>

<?php
include 'podaci.php';
?>

<h2>PREDRAČUN BR. <?php echo $brojrezervacije; ?> ZA USLUGU SMJEŠTAJA</h2>

<div class="prvired">
	<div class="usluga" style="font-weight: bold;">Usluga</div>
	<div class="cijena" style="font-weight: bold;">Cijena</div>
	<div class="kolicina" style="font-weight: bold;">Količina</div>
	<div class="ukupno" style="font-weight: bold;">Ukupno</div>
</div>

<div class="drugired">
	<div class="brojrezervacije" style="font-weight: bold;"><?php echo $usluga; ?></div>
	<div class="datum"><?php echo $datum; ?></div>
	<div class="brojosoba"><?php echo $kolicinaOsoba; ?></div>
	<div class="cijenaeuri"><?php echo $cijenaPoNocenju; ?> €</div>
	<div class="nocenje"><?php echo $brojNocenja; ?></div>
	<div class="ukupnoeuri"><?php echo $ukupnoUsluga; ?> €</div>
</div>

<div class="trecired">
	<div></div>
</div>

<div class="cetvrtired">
	<div class="ukupno1" style="font-weight: bold;">Ukupno</div>
	<div class="ukupno2" style="font-weight: bold;"><?php echo $ukupnoUsluga; ?> €</div>
</div>

<div>
	<br />
	Uključeno u cijenu (bez dodatne naplate): turistička pristojba
</div>
<br />

<h2>DINAMIKA PLAĆANJA</h2>
<div class="prvired">
	<div class="uplata" style="font-weight: bold;">Uplata</div>
	<div class="nacinplacanja" style="font-weight: bold;">Način plaćanja</div>
	<div class="vrijemeplacanja" style="font-weight: bold;">Vrijeme plaćanja</div>
	<div class="iznos" style="font-weight: bold;">Iznos</div>
</div>

<div class="drugired">
	<div class="predujam" style="font-weight: bold;">Akontacija</div>
	<div class="kartica">  <?php echo $akontacijaNačinPlaćanja; ?> </div>
	<div class="vrijemepredujma"><?php echo $akontacijaVrijemePlaćanja; ?></div>
	<div class="iznospredujma" style="font-weight: bold;"><?php echo $akontacijaIznos; ?> €</div>
</div>

<div class="trecired">
	<div class="ostatak" style="font-weight: bold;">Ostatak iznosa</div>
	<div class="kartica"> <?php echo $ostatakNačinPlaćanja; ?> </div>
	<div class="vrijemeostatka"><?php echo $ostatakVrijemePlaćanja; ?></div>
	<div class="iznosostatka" style="font-weight: bold;"><?php echo $ostatakIznos; ?> €</div>
</div>

<div>
	<br />
	<br />
	Uplatom akontacije gost potvrđuje da je upoznat te se slaže s Općim uvjetima pružanja usluga smještaja u privatnim kapacitetima.
</div>

</body>
</html>
