<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="stil.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Zadatak 3</title>
</head>
<body>

<?php
include 'podaci.php';
?>

<h2>PREDRAČUN BR. <?php echo $brojrezervacije; ?> ZA USLUGU SMJEŠTAJA</h2>

<div class="prvired">
	<div class="usluga">Usluga</div>
	<div class="cijena">Cijena</div>
	<div class="kolicina">Količina</div>
	<div class="ukupno">Ukupno</div>
</div>

<div class="drugired">
	<div class="brojrezervacije"><?php echo $usluga; ?></div>
	<div class="datum"></div>
	<div class="brojosoba"><?php echo $kolicinaOsoba; ?></div>
	<div class="cijenaeuri"><?php echo $cijenaPoNocenju; ?> €</div>
	<div class="nocenje"><?php echo $brojNocenja; ?></div>
	<div class="ukupnoeuri"><?php echo $ukupnoUsluga; ?> €</div>
</div>

<div class="trecired">
	<div></div>
</div>

<div class="cetvrtired">
	<div class="ukupno1">Ukupno</div>
	<div class="ukupno2"><?php echo $ukupnoUsluga; ?> €</div>
</div>

<div>
	<br />
	Uključeno u cijenu (bez dodatne naplate): turistička pristojba
</div>
<br />

<h2>DINAMIKA PLAĆANJA</h2>
<div class="prvired">
	<div class="uplata">Uplata</div>
	<div class="nacinplacanja">Način plaćanja</div>
	<div class="vrijemeplacanja">Vrijeme plaćanja</div>
	<div class="iznos">Iznos</div>
</div>

<div class="drugired">
	<div class="predujam"><?php echo $akontacijaNačinPlaćanja; ?></div>
	<div class="kartica">  <?php echo $akontacijaNačinPlaćanja; ?> </div>
	<div class="vrijemepredujma"><?php echo $akontacijaVrijemePlaćanja; ?></div>
	<div class="iznospredujma"><?php echo $akontacijaIznos; ?> €</div>
</div>

<div class="trecired">
	<div class="ostatak"><?php echo $ostatakNačinPlaćanja; ?></div>
	<div class="kartica"> <?php echo $ostatakNačinPlaćanja; ?> </div>
	<div class="vrijemeostatka"><?php echo $ostatakVrijemePlaćanja; ?></div>
	<div class="iznosostatka"><?php echo $ostatakIznos; ?> €</div>
</div>

<div>
	<br />
	<br />
	Uplatom akontacije gost potvrđuje da je upoznat te se slaže s Općim uvjetima pružanja usluga smještaja u privatnim kapacitetima.
</div>

</body>
</html>
